# Generated by Django 4.2.13 on 2024-07-01 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0003_alter_item_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='CommonGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='storage.categorygoods')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_in', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('price_out', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('qnt', models.IntegerField(blank=True, default=1, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=128, null=True)),
                ('condition', models.CharField(blank=True, max_length=256, null=True)),
                ('set', models.CharField(blank=True, max_length=256, null=True)),
                ('parameters', models.CharField(blank=True, max_length=256, null=True)),
                ('note', models.CharField(blank=True, max_length=512, null=True)),
                ('common_goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='storage.commongoods')),
            ],
        ),
        migrations.CreateModel(
            name='Remains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnt', models.IntegerField(blank=True, default=1, null=True)),
                ('goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='storage.goods')),
            ],
        ),
        migrations.CreateModel(
            name='StorageClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('telephone', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.CharField(blank=True, max_length=128, null=True)),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StorageDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='storage.storageclients')),
            ],
        ),
        migrations.CreateModel(
            name='StorageDocTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_qnt', models.IntegerField(blank=True, default=1, null=True)),
                ('goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='storage.goods')),
                ('storage_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.storagedoc')),
            ],
        ),
        migrations.CreateModel(
            name='Storages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=512)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='categorise',
        ),
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='storagedoc',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storage.storages'),
        ),
        migrations.AddField(
            model_name='storagedoc',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remains',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='storage.storages'),
        ),
        migrations.AddField(
            model_name='goods',
            name='storage_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='storage.storagedoc'),
        ),
    ]
