# Generated by Django 4.2.13 on 2024-07-27 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_remove_goods_qnt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorygoods',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categorys'},
        ),
        migrations.AlterModelOptions(
            name='commongoods',
            options={'verbose_name': 'CommonGood', 'verbose_name_plural': 'CommonGoods'},
        ),
        migrations.RemoveField(
            model_name='goods',
            name='storage_doc',
        ),
    ]
