# Generated by Django 4.2.13 on 2024-07-30 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_alter_categorygoods_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='common_goods',
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='storage.categorygoods'),
        ),
        migrations.AddField(
            model_name='goods',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='CommonGoods',
        ),
    ]
