# Generated by Django 4.2.13 on 2024-07-31 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_remove_goods_common_goods_goods_category_goods_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='category',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='name',
        ),
        migrations.CreateModel(
            name='CommonGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='storage.categorygoods')),
            ],
            options={
                'verbose_name': 'CommonGood',
                'verbose_name_plural': 'CommonGoods',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='common_goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.commongoods'),
        ),
    ]
