# Generated by Django 4.2.13 on 2024-08-06 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_alter_remains_goods_alter_storagedoctable_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagedoc',
            name='status',
            field=models.CharField(default='open', max_length=32),
        ),
        migrations.AlterField(
            model_name='storagedoctable',
            name='goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='storage.goods'),
        ),
    ]
