# Generated by Django 4.2.13 on 2024-08-06 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0010_alter_storagedoc_status_alter_storagedoctable_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remains',
            name='goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='storage.goods'),
        ),
        migrations.AlterField(
            model_name='storagedoc',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storage.storages', verbose_name='storage'),
        ),
    ]
