# Generated by Django 4.2.13 on 2024-08-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0011_alter_remains_goods_alter_storagedoc_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagedoctable',
            name='goods_qnt',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='storages',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storages',
            name='location',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
