# Generated by Django 4.2.13 on 2024-10-26 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0013_alter_storagedoc_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageclients',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='storagedoc',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='storage.storageclients'),
        ),
    ]
