# Generated by Django 4.2.13 on 2024-11-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0014_alter_storageclients_name_alter_storagedoc_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorygoods',
            name='api_control',
            field=models.CharField(blank=True, default='no command', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='commongoods',
            name='api_control',
            field=models.CharField(blank=True, default='no command', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='api_control',
            field=models.CharField(blank=True, default='no command', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='remains',
            name='api_control',
            field=models.CharField(blank=True, default='no command', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='storageclients',
            name='api_control',
            field=models.CharField(blank=True, default='no command', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='storagedoc',
            name='api_control',
            field=models.CharField(blank=True, default='no command', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='storagedoctable',
            name='api_control',
            field=models.CharField(blank=True, default='no command', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='storages',
            name='api_control',
            field=models.CharField(blank=True, default='no command', max_length=16, null=True),
        ),
    ]
